// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/conversations": {
    params: {};
  };
  "/dashboard/campaigns": {
    params: {};
  };
  "/dashboard/campaigns/new": {
    params: {};
  };
  "/dashboard/messages": {
    params: {};
  };
  "/dashboard/orders": {
    params: {};
  };
  "/dashboard/leads": {
    params: {};
  };
  "/dashboard/leads/import": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/dev": {
    params: {};
  };
  "/dev/campaigns": {
    params: {};
  };
  "/dev/messages": {
    params: {};
  };
  "/dev/orders": {
    params: {};
  };
  "/dev/leads": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/auth/login" | "/dashboard" | "/dashboard/conversations" | "/dashboard/campaigns" | "/dashboard/campaigns/new" | "/dashboard/messages" | "/dashboard/orders" | "/dashboard/leads" | "/dashboard/leads/import" | "/auth/*" | "/app" | "/app/additional" | "/dev" | "/dev/campaigns" | "/dev/messages" | "/dev/orders" | "/dev/leads";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/dashboard.jsx": {
    id: "routes/dashboard";
    page: "/dashboard" | "/dashboard/conversations" | "/dashboard/campaigns" | "/dashboard/campaigns/new" | "/dashboard/messages" | "/dashboard/orders" | "/dashboard/leads" | "/dashboard/leads/import";
  };
  "routes/dashboard.conversations.jsx": {
    id: "routes/dashboard.conversations";
    page: "/dashboard/conversations";
  };
  "routes/dashboard.campaigns.jsx": {
    id: "routes/dashboard.campaigns";
    page: "/dashboard/campaigns" | "/dashboard/campaigns/new";
  };
  "routes/dashboard.campaigns.new.jsx": {
    id: "routes/dashboard.campaigns.new";
    page: "/dashboard/campaigns/new";
  };
  "routes/dashboard.messages.jsx": {
    id: "routes/dashboard.messages";
    page: "/dashboard/messages";
  };
  "routes/dashboard._index.jsx": {
    id: "routes/dashboard._index";
    page: "/dashboard";
  };
  "routes/dashboard.orders.jsx": {
    id: "routes/dashboard.orders";
    page: "/dashboard/orders";
  };
  "routes/dashboard.leads.jsx": {
    id: "routes/dashboard.leads";
    page: "/dashboard/leads" | "/dashboard/leads/import";
  };
  "routes/dashboard.leads.import.jsx": {
    id: "routes/dashboard.leads.import";
    page: "/dashboard/leads/import";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/additional";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/dev.jsx": {
    id: "routes/dev";
    page: "/dev" | "/dev/campaigns" | "/dev/messages" | "/dev/orders" | "/dev/leads";
  };
  "routes/dev.campaigns.jsx": {
    id: "routes/dev.campaigns";
    page: "/dev/campaigns";
  };
  "routes/dev.messages.jsx": {
    id: "routes/dev.messages";
    page: "/dev/messages";
  };
  "routes/dev._index.jsx": {
    id: "routes/dev._index";
    page: "/dev";
  };
  "routes/dev.orders.jsx": {
    id: "routes/dev.orders";
    page: "/dev/orders";
  };
  "routes/dev.leads.jsx": {
    id: "routes/dev.leads";
    page: "/dev/leads";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.jsx");
  "routes/dashboard.conversations": typeof import("./app/routes/dashboard.conversations.jsx");
  "routes/dashboard.campaigns": typeof import("./app/routes/dashboard.campaigns.jsx");
  "routes/dashboard.campaigns.new": typeof import("./app/routes/dashboard.campaigns.new.jsx");
  "routes/dashboard.messages": typeof import("./app/routes/dashboard.messages.jsx");
  "routes/dashboard._index": typeof import("./app/routes/dashboard._index.jsx");
  "routes/dashboard.orders": typeof import("./app/routes/dashboard.orders.jsx");
  "routes/dashboard.leads": typeof import("./app/routes/dashboard.leads.jsx");
  "routes/dashboard.leads.import": typeof import("./app/routes/dashboard.leads.import.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/dev": typeof import("./app/routes/dev.jsx");
  "routes/dev.campaigns": typeof import("./app/routes/dev.campaigns.jsx");
  "routes/dev.messages": typeof import("./app/routes/dev.messages.jsx");
  "routes/dev._index": typeof import("./app/routes/dev._index.jsx");
  "routes/dev.orders": typeof import("./app/routes/dev.orders.jsx");
  "routes/dev.leads": typeof import("./app/routes/dev.leads.jsx");
};